### PR TITLE
Adjust citus resources

### LINKED ISSUE #9203: Increase resources to database node pools
### Problem

Performance testing still shows a number of endpoints with terrible RPS. Due to time constraints we will temporarily increase database resources to increase their performance.

### Solution

Change worker node pools to n2-custom-12-40960

### Alternatives

_No response_

### PR DESCRIPTION
**Pull request by xin-hedera**
**Description**:

**Related issue(s)**:

Fixes #9203 

**Notes for reviewer**:

Require changing worker node-pool instance type to at least n2-custom-12-40960 (12 CPUs, 40GB memory) prior to deploy the changes.

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

### CODE REVIEW

**Review by jascks — DISMISSED** [review]
LGTM

**Review by steven-sheehy — COMMENTED** [review]
We also need to update docs/database/README.md. Both the setup section and the `Database migration from V1 to V2` section

**Review by steven-sheehy — APPROVED** [review]

**Review by mgoelswirlds — APPROVED** [review]
LGTM

**Review by edwin-greene — APPROVED** [review]
Looks good

**Pull request merged**
