### PR TITLE
Update mainnet-staging to v0.117.0-rc1

### PR DESCRIPTION
**Pull request by steven-sheehy**
**Description**:

Update mainnet-staging to v0.117.0-rc1

**Related issue(s)**:

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

### CODE REVIEW

**Review by xin-hedera — DISMISSED** [review]
LGTM

**Review by edwin-greene — DISMISSED** [review]

**Review by jnels124 — DISMISSED** [review]
LGTM - Note air drop parameters were not configured for the last release. Not sure if there are available params now.

**Comment by steven-sheehy** [comment]
Thanks, I've updated the k6 config for airdrops

**Review by jnels124 — APPROVED** [review]
LGTM

**Review by edwin-greene — APPROVED** [review]

**Pull request merged**
