### PR TITLE
Rename windows-incompatible files

### LINKED ISSUE #2027: Git checkout fails on windows
**Detailed Description**
Git checkout on windows fails due to colons in filenames, leaving the working tree in a bad state.

**Actual Behavior**
```shell
❯ git version
git version 2.27.0.windows.1

❯ git clone https://github.com/si618/hedera-mirror-node.git
Cloning into 'hedera-mirror-node'...
remote: Enumerating objects: 36499, done.
remote: Counting objects: 100% (259/259), done.
remote: Compressing objects: 100% (202/202), done.
remote: Total 36499 (delta 73), reused 154 (delta 31), pack-reused 36240
Receiving objects: 100% (36499/36499), 114.01 MiB | 5.34 MiB/s, done.
Resolving deltas: 100% (21767/21767), done.
error: invalid path 'hedera-mirror-importer/src/test/resources/data/recordstreams/v1/record0.0.3/2019-07-01T14:13:00.317763Z.rcd'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'
```

**Expected Behavior**
Git clone and checkout succeeds.

**Environment:**
- OS: Windows 10

**Additional Context**
Related to [issue #281](https://github.com/hashgraph/hedera-mirror-node/issues/281)

### PR DESCRIPTION
**Pull request by si618**
**Detailed description**:
Rename files incompatible with windows and update references to affected files.

**Which issue(s) this PR fixes**:
Fixes #2027

### CODE REVIEW

**Review by steven-sheehy — COMMENTED** [review]
Hi @si618 thanks for your contribution! It looks good so far but seems there's some additional tests in importer than might need to be fixed. You can ignore the Rosetta check failing, we need to skip those for forks since they use a secret.

**Comment by si618** [comment]
No worries Steven, I'm still in the process of setting things up, but once a build is working and docker is running I'll try and get the tests passing locally against my branch.

FWIW, as the files all started with the same date and hour, I searched for `2019-07-01T14` and changed all references, but there could certainly be some code that I missed e.g. if the tests loaded all files found under a directory.

**Comment by Nana-EC** [comment]
> No worries Steven, I'm still in the process of setting things up, but once a build is working and docker is running I'll try and get the tests passing locally against my branch.
> 
> FWIW, as the files all started with the same date and hour, I searched for `2019-07-01T14` and changed all references, but there could certainly be some code that I missed.

Nice one. 
We tried to avoid this issue in our updates and when adding new files once we came across it, but looks like we missed the early v1 files under `hedera-mirror-importer/src/test/resources/data/recordstreams/v1` which is what you've nicely found here.
Thanks

**Comment by si618** [comment]
Hi again, was able to build and run tests, turns out I was over-zealous in my renaming, incorrectly including a period. Fix pushed.

One test was throwing an error locally

```
❯ .\mvnw.cmd clean package
...
[ERROR]   PubSubRecordParserTest.testPubSubExporter » IllegalState Failed to load Applic...
[INFO]
[ERROR] Tests run: 1243, Failures: 0, Errors: 1, Skipped: 4
```
Can post full stack trace, but looks to be a timeout
```
-------------------------------------------------------------------------------
Test set: com.hedera.mirror.importer.parser.record.pubsub.PubSubRecordParserTest
-------------------------------------------------------------------------------
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 44.74 s <<< FAILURE! - in com.hedera.mirror.importer.parser.record.pubsub.PubSubRecordParserTest
com.hedera.mirror.importer.parser.record.pubsub.PubSubRecordParserTest.testPubSubExporter  Time elapsed: 0 s  <<< ERROR!
java.lang.IllegalStateException: Failed to load ApplicationContext
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'webHandler' defined in class path resource [org/springframework/boot/autoconfigure/web/reactive/WebFluxAutoConfiguration$EnableWebFluxConfiguration.class]: Initialization of bean failed;
...
nested exception is java.util.concurrent.TimeoutException
```

Next up, hedera-mirror-rest/.husky/pre-commit hook was failing when trying to commit
```
error: cannot spawn hedera-mirror-rest\.husky/pre-commit: No such file or directory
```
Running npx in hook manually worked fine
```shell
❯ npx --no-install pretty-quick --staged
🔍  Finding changed files since git revision 75d15114.
🎯  Found 0 changed files.
✅  Everything is awesome!
```
Possibly another [windows specific issue](https://github.com/typicode/husky/issues/864)?

Finally, ran into a problem building the rosetta api, this also looks to be an [issue with go](https://github.com/golang/go/issues/43195#issuecomment-747641758) on windows.

```
❯ java --version
openjdk 11.0.11 2021-04-20
OpenJDK Runtime Environment Microsoft-22268 (build 11.0.11+9)
OpenJDK 64-Bit Server VM Microsoft-22268 (build 11.0.11+9, mixed mode)

❯ go version
go version go1.16.4 windows/amd64

❯ gcc --version
gcc.exe (tdm64-1) 10.3.0

> .\mvnw.cmd clean package -DskipTests
...
[INFO] --- mvn-golang-wrapper:2.3.8:build (default-build) @ hedera-mirror-rosetta ---
[INFO] Scanning maven dependencies
[WARNING] Value GOPATH is replaced by environment value.
[INFO] Prepared command line : bin\go.exe build -buildmode=default -o C:\Code\Crypto\Hashgraph\hedera-mirror-node\hedera-mirror-rosetta\bin\hedera-mirror-rosetta -a -i -race
[ERROR]
[ERROR] ---------Exec.Err---------
[ERROR] go build: -i flag is deprecated
[ERROR] # github.com/hashgraph/hedera-mirror-node/hedera-mirror-rosetta/cmd
[ERROR] C:/tools/TDM-GCC-64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/lib/../lib/libmsvcrt.a(/2203): duplicate symbol reference: _unlock_file in both libgcc(.text) and libgcc(.data)
[ERROR] libgcc(.text): relocation target ___chkstk_ms not defined
[ERROR] libgcc(.text): relocation target atexit not defined
[ERROR]
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Hedera Mirror Node 0.35.0-SNAPSHOT:
[INFO]
[INFO] Hedera Mirror Node ................................. SUCCESS [  3.161 s]
[INFO] Hedera Mirror Node Importer ........................ SUCCESS [ 30.470 s]
[INFO] Hedera Mirror Data Generator ....................... SUCCESS [  4.269 s]
[INFO] Hedera Mirror Node Protobuf ........................ SUCCESS [  3.372 s]
[INFO] Hedera Mirror Node GRPC API ........................ SUCCESS [ 10.649 s]
[INFO] Hedera Mirror Node Monitor ......................... SUCCESS [  5.234 s]
[INFO] Hedera Mirror Node REST API ........................ SUCCESS [ 29.525 s]
[INFO] Hedera Mirror Node Rosetta REST API ................ FAILURE [ 41.627 s]
[INFO] Hedera Mirror Node Test ............................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  02:09 min
[INFO] Finished at: 2021-05-31T21:24:29+09:30
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.igormaznitsa:mvn-golang-wrapper:2.3.8:build (default-build) on project hedera-mirror-rosetta: Process exit code : 2 -> [Help 1]

**Review by steven-sheehy — APPROVED** [review]
LGTM. The `PubSubRecordParserTest` is a known transient failure not related to your changes that we need to address. Thanks for your contribution!

**Comment by steven-sheehy** [comment]
Sorry, one more thing. Do you mind GPG [signing](https://docs.github.com/en/github/authenticating-to-github/managing-commit-signature-verification/about-commit-signature-verification) your commits? You can then [re-sign](https://superuser.com/questions/397149/can-you-gpg-sign-old-commits) the past commits and force push.

**Review by ijungmann — APPROVED** [review]

**Review by xin-hedera — DISMISSED** [review]
LGTM

**Review by steven-sheehy — APPROVED** [review]

**Pull request merged**
