### PR TITLE
fix: Fix historical erc tests after conflicting pr merges

### PR DESCRIPTION
**Pull request by kselveliev**
**Description**:

After back to back merging in main the following prs ->
https://github.com/hashgraph/hedera-mirror-node/pull/9303
and 
https://github.com/hashgraph/hedera-mirror-node/pull/9272

this broke the tests 

[9272](https://github.com/hashgraph/hedera-mirror-node/pull/9272) contains the newly introduced contract in solidity_historical folder
`ERCTestContractHistorical.sol` which uses ERC openzeppelin.

After merging of [9303](https://github.com/hashgraph/hedera-mirror-node/pull/9303) all of the others historical solidity contracts were moved to testHistorical source directory.
Except for` ERCTestContractHistorical.sol` since the pr did not know about it yet.

This PR adds the `ERCTestContractHistorical.sol` testHistorical source directory.
Unfortunately [9303](https://github.com/hashgraph/hedera-mirror-node/pull/9303) removed the legacy openzeppelin contract download and extraction causing  `ERCTestContractHistorical.sol `compilation to fail.
Reflecting to this comment https://github.com/hashgraph/hedera-mirror-node/pull/9303#discussion_r1751827598. It seems like we actually need the download and extraction tasks. It worked without `ERCTestContractHistorical.sol `because no other class in the testHistorical directory used the openzeppelin library. But now they use it.

This PR modifies:
Modified `build.gradle` in web3 add legacy openzeppelin extraction tasks
Moved `ERCTestContractHistorical.sol `into testHistorical folder

**Related issue(s)**:

Fixes #

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

### CODE REVIEW

**Comment by steven-sheehy** [comment]
See [this](https://github.com/hashgraph/hedera-mirror-node/pull/9303#discussion_r1750740836) comment. We should try to use versioned import statements.

**Comment by kselveliev** [comment]
> See [this](https://github.com/hashgraph/hedera-mirror-node/pull/9303#discussion_r1750740836) comment. We should try to use versioned import statements.

Need some time to explore this more but just with   `import "https://github.com/OpenZeppelin/openzeppelin-contracts/blob/v4.9.3/contracts/token/ERC20/IERC20.sol";` it doesn't work. Even if I add the path to allowPaths for the solidity plugin to check it.

**Comment by steven-sheehy** [comment]
What about the raw variant? `https://raw.githubusercontent.com/OpenZeppelin/openzeppelin-contracts/v4.9.3/contracts/token/ERC20/IERC20.sol`

**Comment by kselveliev** [comment]
> https://raw.githubusercontent.com/OpenZeppelin/openzeppelin-contracts/v4.9.3/contracts/token/ERC20/IERC20.sol

Same as before.

Error: Source "https://raw.githubusercontent.com/OpenZeppelin/openzeppelin-contracts/v4.9.3/contracts/token/ERC20/IERC20.sol" not found: File not found.
 --> src/testHistorical/solidity/ERCTestContractHistorical.sol:4:1:

Maybe it’s a limitation of the solidity plugin since this works in remix. I thinks it’s worth exploring with Bilyana tomorrow.

**Review by bilyana-gospodinova — APPROVED** [review]
LGTM. I couldn't make the URL imports work as well. Probably a limitation of the plugin.

**Review by steven-sheehy — APPROVED** [review]

**Pull request merged**
