### PR TITLE
remove operator balance override for testnet-na

### PR DESCRIPTION
**Pull request by jnels124**
remove operator balance override for testnet-na

### CODE REVIEW

**Comment by steven-sheehy** [comment]
We should just wait for a GA tag update and do it together.

**Review by xin-hedera — APPROVED** [review]
LGTM

**Review by mgoelswirlds — APPROVED** [review]
LGTM

**Comment by jnels124** [comment]
> We should just wait for a GA tag update and do it together.

GA was cut and need this for acceptance to pass

**Pull request merged**
