### PR TITLE
Bump version for v0.30.0-rc1

### PR DESCRIPTION
**Pull request by Nana-EC**
**Detailed description**:
Bump to v0.30.0-rc1

**Which issue(s) this PR fixes**:
Fixes #<issue number>

**Special notes for your reviewer**:

**Checklist**
- [ ] Documentation added
- [ ] Tests updated

### CODE REVIEW

**Review by steven-sheehy — DISMISSED** [review]
LGTM

**Comment by steven-sheehy** [comment]
It would be good if https://github.com/hashgraph/hedera-mirror-node/pull/1747 could be merged first and this rebased so we can confirm that chart/install job succeeds.

**Review by xin-hedera — DISMISSED** [review]
LGTM

**Review by steven-sheehy — APPROVED** [review]
My chart install fix didn't work, but that's not related to this PR.

**Review by xin-hedera — APPROVED** [review]
LGTM

**Pull request merged**
