### PR TITLE
Fix value of v in contract result APIs for legacy Ethereum transactions

### LINKED ISSUE #8597: Some transactions with signature v values set to 1 cause the go ethereum client to fail when trying to unmarshal them.
### Description

The following transactions on mainnet cannot be unmarshalled using the go ethereum client:
`0x65486c84522a4f581aeaf5d2b17dc7993c76c916e78158f375d0c89d625e4979`
`0x814b3b545d381b61564733c76cd281f9a1903874319c6594bc6828adba42a08b`
`0x1c9a630ae53193c4f982e48a28247cb561f7e7ff2bd99cbbbaa270aab23c0bf4`

The following transaction on testnet cannot be unmarshalled using the go ethereum client:
`0xaacb25c6bd26870204b566b138a37b33a17d4e44d7dcd9c05678a3f46352f7a0`

Setting the signature v values to 37 or 38 allows them to be unmarshalled in the go-client.  These are type 0 (Legacy) transactions.

### Steps to reproduce

Relay issue [2500](https://github.com/hashgraph/hedera-json-rpc-relay/issues/2500) has a reproducer.

### Additional context

_No response_

### Hedera network

mainnet

### Version

v0.106.1

### Operating system

Linux

### PR DESCRIPTION
**Pull request by steven-sheehy**
**Description**:

Fix the return value of v in the contract results APIs to use the actual `signature_v` field instead of `recovery_id` for legacy Ethereum transactions.

**Related issue(s)**:

Fixes #8597

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

### CODE REVIEW

**Review by lukelee-sl — APPROVED** [review]
LGTM

**Review by IvanKavaldzhiev — APPROVED** [review]
LGTM

**Review by Nana-EC — APPROVED** [review]
LG 🙌🏾

**Review by ebadiere — APPROVED** [review]
Thank you.

**Pull request merged**
