### PR TITLE
Improve GraphQL Chart Test

### LINKED ISSUE #5518: Chart workflow fails during GraphQL Helm test
### Description

The GraphQL Helm test sporadically [fails](https://github.com/hashgraph/hedera-mirror-node/actions/runs/4290666403/jobs/7474919041) in CI during the charts workflow.

### Steps to reproduce

Run charts install workflow

### Additional context

```
------------------------------------------------------------------------------------------------------------------------
==> Logs of container hedera-mirror-fbm9z10oue-graphql-test
------------------------------------------------------------------------------------------------------------------------
newman

GraphQL API

❏ Negative Tests
↳ Get Account Non Existing field
  POST http://hedera-mirror-fbm9z10oue-graphql:80/graphql/alpha [200 OK, 288B, 282ms]
  ✓  Non Existing Field

↳ By Alias (Unimplemented)
  POST http://hedera-mirror-fbm9z10oue-graphql:80/graphql/alpha [200 OK, 243B, 99ms]
  ✓  By Id (Unimplemented)

→ Get Account
  POST http://hedera-mirror-fbm9z10oue-graphql:80/graphql/alpha [200 OK, 96B, 133ms]
  1. Get By Entity Id (All Fields)

┌─────────────────────────┬────────────────────┬───────────────────┐
│                         │           executed │            failed │
├─────────────────────────┼────────────────────┼───────────────────┤
│              iterations │                  1 │                 0 │
├─────────────────────────┼────────────────────┼───────────────────┤
│                requests │                  3 │                 0 │
├─────────────────────────┼────────────────────┼───────────────────┤
│            test-scripts │                  3 │                 0 │
├─────────────────────────┼────────────────────┼───────────────────┤
│      prerequest-scripts │                  0 │                 0 │
├─────────────────────────┼────────────────────┼───────────────────┤
│              assertions │                  3 │                 1 │
├─────────────────────────┴────────────────────┴───────────────────┤
│ total run duration: 850ms                                        │
├──────────────────────────────────────────────────────────────────┤
│ total data received: 412B (approx)                               │
├──────────────────────────────────────────────────────────────────┤
│ average response time: 171ms [min: 99ms, max: 282ms, s.d.: 79ms] │
└──────────────────────────────────────────────────────────────────┘

  #  failure    detail                                     
                                                           
 1.  TypeError  Get By Entity Id (All Fields)              
                Cannot convert undefined or null to object 
                at assertion:0 in test-script              
                inside "Get Account"                       
```

### Hedera network

other

### Version

main

### Operating system

None

### PR DESCRIPTION
**Pull request by jnels124**
**Description**:
update default values for ci chart install workflow

**Related issue(s)**:

Fixes #5518 

**Notes for reviewer**:

**Checklist**

- [x] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

### CODE REVIEW

**Comment by mgoelswirlds** [comment]
There was a timing value Steven mentioned that also needed editing right?

**Review by edwin-greene — DISMISSED** [review]
Looks good to me.

**Comment by jnels124** [comment]
@mgoelswirlds You are correct

**Review by steven-sheehy — APPROVED** [review]
LGTM

**Review by xin-hedera — APPROVED** [review]

**Review by mgoelswirlds — APPROVED** [review]

**Pull request merged**
