### PR TITLE
Fill in entities from a file

### PR DESCRIPTION
**Pull request by steven-sheehy**
**Detailed description**:
- Fills in missing t_entities from a file named `accountInfo.txt` dropped in `/var/lib/mirror-node`
- File is in format of base64 encoded AccountInfo protobuf separated by a newline character
- Flyway Java migration now can be a Spring bean and is automatically found and ran

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:
Tested locally with the file provided by engineering from the mainnet saved state. We'll need to get saved state for testnet and mainnet before deploying.

**Checklist**
- [ ] Documentation added
- [x] Tests updated

### CODE REVIEW

**Comment by mike-burrage-hedera** [comment]
Should this be a repeatable migration (named R1.11.6 instead of V1.11.6) that should rename the accountinfo file when done (to indicate it completed - ".timestamp.old")? This will allow us to run it again more easily if necessary.

It also doesn't properly handle accounts that have been updated since whenever this snapshot was taken (if there are any). Such as if just an expiry was updated (we won't have the rest of the attributes). I don't know what accounts are in the data file or when it was taken, so possibly this isn't relevant for today.

**Comment by steven-sheehy** [comment]
> Should this be a repeatable migration (named R1.11.6 instead of V1.11.6) that should rename the accountinfo file when done (to indicate it completed - ".timestamp.old")? This will allow us to run it again more easily if necessary.

Don't think it needs to be as this just needs to do a one time data import to fill in missing entites before restart event. But Greg can confirm.

> It also doesn't properly handle accounts that have been updated since whenever this snapshot was taken (if there are any). Such as if just an expiry was updated (we won't have the rest of the attributes). I don't know what accounts are in the data file or when it was taken, so possibly this isn't relevant for today.

This should be ran with saved state from the time of a restart event (or a little before). You're right though I probably only should insert rows that are missing. But then it also needs to handle updating rows that have incomplete data like those that came in for a cryptotransfer.

**Comment by mike-burrage-hedera** [comment]
>> Should this be a repeatable migration (named R1.11.6 instead of V1.11.6) that should rename the accountinfo file when done (to indicate it completed - ".timestamp.old")? This will allow us to run it again more easily if necessary.
>> 
> Don't think it needs to be as this just needs to do a one time data import to fill in missing entites before restart event. But Greg can confirm.

I was thinking more along the lines of if we have another "restart" after this migration has been applied (and potentitally after we have 1.11.7+ which would mean we couldn't just remove 1.11.6 from the flyway_schema_history to run it again). If we make it repeatable we can just put an accountinfo file there again.

**Comment by mike-burrage-hedera** [comment]
Although - not knowing the timestamp on the AccountInfo (in either the file or db) makes determining what info to update more complex.

**Comment by gregscullard** [comment]
Here are some thoughts for discussion:

-If we can find a `create account/file/contract` transaction in `t_transactions`, we shouldn't attempt to update the entity at all.

-If an entity has one or more `update` transaction(s) associated with it in `t_transactions`, we need to tread carefully, an update doesn't necessarily update all fields, the `key` could be updated while other parameters aren't.

In this case, if the `expiration_time`, `auto_renew`, `fk_proxy_acc_id` or `key` are null in the database, it's safe to assume we can update, but only update those values that are null, not those that have values already, they can only have been set by an update transaction.

If an entity is known as deleted from the input file, but not marked `deleted` in the database, we can update the deleted flag to true. If a `delete` transaction exists in the database, the entity should already be marked `deleted=true`.

I'd also recommend we backup the entities table to `t_entities_`+execution date/time, before making any changes so that we have reference data to go back to in the event we need it.

**Comment by mike-burrage-hedera** [comment]
Please don't create a backup table/schema - there's no reason this should modify the schema at all. Backup the data via a pg_backup if you have to.

**Comment by steven-sheehy** [comment]
@gregscullard I think I've addressed your comments if you'd like to give it another look.

**Comment by gregscullard** [comment]
Looks good from here

**Pull request merged**
