### PR TITLE
Store transaction bytes (optional)

### LINKED ISSUE #414: Add raw transaction bytes to t_transactions table (optionally)
**Problem**
For 3rd party integrations there are times when the raw bytes are required for validation, audit, etc. This feature allows integrators to get at any other fields not parsed by the mirror node without any further modifications to the mirror node.

**Solution**
- Add a new field to the t_transactions table named transaction_bytes.
- Add a property to the RecordParserProperties to disable this behavior by default.

**Alternatives**
None that I can see besides parsing the files again when the raw bytes are needed.

**Additional Context**
I have already done a test run of these changes in my own fork - I am available to do the work.

### PR DESCRIPTION
**Pull request by carlcherry**
**Detailed description**:

**Which issue(s) this PR fixes**:
Fixes #414

**Special notes for your reviewer**:

**Checklist**
- [ ] Documentation added
- [x] Tests updated

### CODE REVIEW

**Comment by mike-burrage-hedera** [comment]
We're testing out if there's a need to add an `alter table t_transactions alter column transaction_bytes set storage external` in the DB script. If the protobuf isn't really compressible, the default storage of extended would be wasting DB CPU cycles.

**Comment by carlcherry** [comment]
I can just add the set storage external line and push another commit.

**Comment by mike-burrage-hedera** [comment]
Sounds good. Thanks.

**Comment by carlcherry** [comment]
Done.

**Pull request merged**
