### PR TITLE
HIP-584: Copied RevokeKycPrecompile

### LINKED ISSUE #5659: HIP-584: Provide implementation for RevokeKycPrecompile
### Problem

We need default implementations for precompiles related to `RevokeKycPrecompile` logic, so we should copy needed logic from `hedera-services` into `hedera-mirror-web3`.

### Solution

- Copy precompile logic for `RevokeKycPrecompile`
- Integrate `RevokeKycPrecompile` with the Store interface.
- Add javadoc describing what has changed and how we integrated it in the `mirror-node`’s code base
- Create integration tests in `ContractCallServicePrecompileTest` in `hedera-mirror-web3` and validate that the return gas estimates in the desired range with offset between 5% and 20% more than the actual gas used

### Alternatives

_No response_

### PR DESCRIPTION
**Pull request by kselveliev**
**Description**:
Changes in this PR:

1. Copied **RevokeKycPrecompile** from hedera-services
    -  Remove unneeded **ledgers**, **aliases**, **sigsVerifier**, **sideEffects**, **infrastructureFactory** from constructor
    -  Added **revokeKycLogic** in the precompile constructor
    -  Added documentation for what has changed
3. Created **RevokeKycPrecompileTest** and added unit tests in it
4. Added new bean **revokeKycPrecompile** in **ServiceConfiguration**
5. Added integration **REVOKE_TOKEN_KYC** test in **ContractCallServicePrecompileTest**
6. Added new constant in **AccessorBasedUsages** for **TokenRevokeKycFromAccount**

**Related issue(s)**:

Fixes #5659 

**Notes for reviewer**:

**Checklist**

### CODE REVIEW

**Review by steven-sheehy — APPROVED** [review]
LGTM. Not sure why checks are frozen. Can you merge from main to trigger checks?

**Review by IvanKavaldzhiev — DISMISSED** [review]
LGTM

**Review by dikel — APPROVED** [review]
LGTM

**Review by IvanKavaldzhiev — APPROVED** [review]
LGTM

**Review by agadzhalov — APPROVED** [review]

**Comment by agadzhalov** [comment]
LGTM

**Review by steven-sheehy — APPROVED** [review]

**Pull request merged**
