### PR TITLE
Enable previously commented out tests

### LINKED ISSUE #7154: Enable previously commented out tests
### Problem

There are four tests  were commented out in the past due to failures or inaccuracies. The tests are the following.

call.feature:
Then I call function with nested deploy using create function
Then I call function with nested deploy using create2 function

estimatePrecompile.feature:
Then I call estimateGas with pseudo random seed
Then I call estimateGas with pseudo random number

### Solution

Uncomment tests.

### Alternatives

_No response_

### PR DESCRIPTION
**Pull request by yiliev0**
**Description**: Enabling previously commented out tests.
call.feature-> Tested against local and integration environment.
Then I call function with nested deploy using create function
Then I call function with nested deploy using create2 function

estimatePrecompile.feature-> Tested against local, preview and integration environment.
Then I call estimateGas with pseudo random seed
Then I call estimateGas with pseudo random number

**Related issue(s)**:

Fixes #7154

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

### CODE REVIEW

**Comment by steven-sheehy** [comment]
Need to test against testnet as well since I believe they might be exchange rate related

**Comment by yiliev0** [comment]
@steven-sheehy Tested PRNG tests against testnet as well and the tests pass successfully.

**Review by steven-sheehy — APPROVED** [review]
LGTM

**Review by xin-hedera — APPROVED** [review]
LGTM

**Comment by steven-sheehy** [comment]
If you merge from main you should be able to retain approvals and merge to main.

**Pull request merged**
