### PR TITLE
Bump versions for 0.26.0-beta1

### PR DESCRIPTION
**Pull request by ijungmann**
**Detailed description**:

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:

**Checklist**
- [ ] Documentation added
- [ ] Tests updated

### CODE REVIEW

**Review by steven-sheehy — CHANGES_REQUESTED** [review]
need to helm dep up charts/hedera-mirror

**Comment by ijungmann** [comment]
> need to helm dep up charts/hedera-mirror

Got it, done

**Review by Nana-EC — APPROVED** [review]
LGTM

**Review by steven-sheehy — APPROVED** [review]
LGTM

**Review by xin-hedera — APPROVED** [review]
LGTM

**Pull request merged**
