### PR TITLE
Increase rest pg pool timeouts

### PR DESCRIPTION
**Pull request by xin-hedera**
**Detailed description**:
Increase the defaults of rest pg pool connection timeout and statement timeout to 20s

**Which issue(s) this PR fixes**:
Fixes #<issue number>

**Special notes for your reviewer**:

**Checklist**
- [x] Documentation added
- [ ] Tests updated

### CODE REVIEW

**Review by Nana-EC — DISMISSED** [review]
LGTM

**Review by ijungmann — APPROVED** [review]

**Review by steven-sheehy — CHANGES_REQUESTED** [review]
Update docs

**Review by ijungmann — APPROVED** [review]

**Review by Nana-EC — APPROVED** [review]
LGTM

**Review by ijungmann — APPROVED** [review]

**Review by steven-sheehy — APPROVED** [review]
LGTM

**Pull request merged**
