### PR TITLE
Fix accounts performance regression caused by account_contract view

### PR DESCRIPTION
**Pull request by xin-hedera**
**Description**:

This PR fixes the `/accounts` performance regression caused by the `account_contract` view.

- Drop the view and use a function to get the union query with order

**Related issue(s)**:

Relates to #2794

**Notes for reviewer**:

For the view `account_contract` `account_query union contract_query`, without a consistent `order by` in the two sub queries, when the view is used in accounts.js `select fields from account_contract order by id (asc|desc) limit $1`, pg planner can't push the limit down so ends up with full scans of `entity` and `contract` table.

Tested the fix in perfnet, the QPS goes back the level of rc2.

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

### CODE REVIEW

**Review by ijungmann — APPROVED** [review]
LGTM

**Review by steven-sheehy — APPROVED** [review]
Having 3 views defeats the purpose of having a reusable view. But to avoid churn let's get this in and in main drop all the views and go back to manual unions.

**Review by Nana-EC — DISMISSED** [review]
LGTM

**Review by ijungmann — APPROVED** [review]

**Review by Nana-EC — APPROVED** [review]
LGTM

**Pull request merged**
