### PR TITLE
Update README.md

### LINKED ISSUE #5108: Incorrect monitor nft mint example scenario in README
### Description

The nft mint example in monitor README should have `type: NON_FUNGIBLE_UNIQUE` instead of `tokenType: NON_FUNGIBLE_UNIQUE` 

### Steps to reproduce

n/a

### Additional context

_No response_

### Hedera network

other

### Version

v0.71.0-SNAPSHOT

### Operating system

None

### PR DESCRIPTION
**Pull request by Neurone**
**Description**:
This PR modifies the documentation in orfer to fix the NFT scenario.

**Related issue(s)**:

Fixes #5108 

**Notes for reviewer**:

The correct attribute is `type`, not `tokenType` (https://github.com/hashgraph/hedera-mirror-node/blob/e59c02d0506d1287914dd28a063d8fec2410f619/hedera-mirror-monitor/src/main/java/com/hedera/mirror/monitor/publish/transaction/token/TokenMintTransactionSupplier.java#L56).

Using `tokenType` the field is ignored, and the scenario tries to mint a fungible token.

**Checklist**

- [x] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

### CODE REVIEW

**Comment by xin-hedera** [comment]
@Neurone thanks for the PR. can you fix the DCO issue so it can be merged?

**Comment by Neurone** [comment]
> @Neurone thanks for the PR. can you fix the DCO issue so it can be merged?

It should be ok now.

**Review by xin-hedera — APPROVED** [review]
LGTM

**Comment by xin-hedera** [comment]
@Neurone  can you push two commits with the first changing sth in the README and the second reverting the changes? That way it should trigger the workflow runs so we can merge the PR.

**Pull request merged**
