### PR TITLE
Fix Citus indexes and properties

### LINKED ISSUE #6684: Adjust Citus settings
### Description

Some of the index and PostgreSQL properties are incorrect for Citus and can cause it to get OOMKilled.

### Steps to reproduce

Run Citus

### Additional context

_No response_

### Hedera network

other

### Version

main

### Operating system

None

### PR DESCRIPTION
**Pull request by steven-sheehy**
**Description**:

* Change crypto transfer index to exclude staking account
* Change `maintenance_work_mem` from `2GB` to `256MB`
* Change `shared_buffers` from `12GB` to `6GB`
* Cleanup the REST, Rosetta, and Web3 dashboards
* Fix Spring repository latency calculation in dashboards
* Mark all dashboards as not editable
* Merge transaction payer account indexes into one
* Remove extra token balance index

**Related issue(s)**:

Fixes #6684

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

### CODE REVIEW

**Review by jascks — DISMISSED** [review]
LGTM

**Review by jascks — APPROVED** [review]
Re-LGTM.

**Review by xin-hedera — APPROVED** [review]
LGTM

**Review by edwin-greene — APPROVED** [review]
Looks good

**Pull request merged**
