### PR TITLE
Bump Spring Boot from 2.7 to 3.1

### LINKED ISSUE #6035: Bump Spring Boot to latest
### Problem

The 2.7 version of Spring Boot has vulnerabilities in transitive dependencies like SnakeYAML 1.x that cause our application to report as vulnerable. Upgrading to the latest Spring Boot will resolve this.

### Solution

* Update Spring Boot to 3.1

### Alternatives

_No response_

### PR DESCRIPTION
**Pull request by steven-sheehy**
**Description**:

* Bump Spring Boot from `2.7` to `3.1`
* Bump Spring Cloud from `2021.0.5` to `2022.0.2`
* Bump Spring Cloud GCP from `3.5.0` to `4.3.1`
* Change `com.vladmihalcea` dependencies to `io.hypersistence` and adjust imports
* Change from `String` to class based `@Type` imports in Hibernate 6
* Change `javax` imports to `jakarta`
* Change `spring.redis` properties to `spring.data.redis`
* Fix `AddressBookEntry.serviceEndpoints` lazy init errors by wrapping in a transaction
* Fix invalid `spring.config.active.on-profile` property in monitor
* Fix various deprecation warnings

**Related issue(s)**:

Fixes #6035

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

### CODE REVIEW

**Review by jascks — DISMISSED** [review]
This is awesome. Thank you for pulling this all together and getting us all the way up to 3.1!

**Review by xin-hedera — DISMISSED** [review]
LGTM

**Review by xin-hedera — APPROVED** [review]

**Review by jascks — APPROVED** [review]
LGTM still

**Review by jnels124 — APPROVED** [review]
LGTM

**Pull request merged**
