### PR TITLE
Create entities during balance initialization

### LINKED ISSUE #4763: Cannot Query Account Balances in v0.67.1
### Description

We have been using `balances` API for checking account balances. After we upgraded from `v0.65.0` to `v0.67.1`, we found that the API no longer works the same.

### Steps to reproduce

1. Upgrade hedera-mirror node from `v0.65.0` to `v0.67.1` docker image
2. Perform the command `curl -s 'http://x.x.x.x:5551/api/v1/balances?account.id=0.0.account_id'` and the following is returned now:
```
{"timestamp":null,"balances":[],"links":{"next":null}}
```
3. Perform the command `curl -s 'http://x.x.x.x:5551/api/v1/balances?account.id=0.0.account_id&timestamp=1666855809.983411175'` and the following will be returned instead:
```
{"timestamp":"1666845001.084929000","balances":[{"account":"0.0.account_id","balance":0,"tokens":[]}],"links":{"next":null}}
```

### Additional context

_No response_

### Hedera network

mainnet

### Version

v0.67.1

### Operating system

Linux

### PR DESCRIPTION
**Pull request by steven-sheehy**
**Description**:

**Related issue(s)**:

Fixes #4763

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

### CODE REVIEW

**Comment by mgoelswirlds** [comment]
Do we need to listen for AccountBalanceFileParsedEvent and re-run if entity table is empty and it hasn't already ran since last startup as per the ticket description?

**Review by mgoelswirlds — APPROVED** [review]
LGTM.

**Comment by mgoelswirlds** [comment]
Just a followup on that comment. We want to rerun the migration on an empty balance table right and not an empty entity table?

**Review by xin-hedera — APPROVED** [review]
LGTM

**Comment by steven-sheehy** [comment]
> Just a followup on that comment. We want to rerun the migration on an empty balance table right and not an empty entity table?

Right, must've mis-typed that in the original ticket.

**Pull request merged**
