### PR TITLE
Remove EntityId.getType()

### PR DESCRIPTION
**Pull request by steven-sheehy**
**Description**:

* Remove `EntityId.getType()`
* Remove `EntityTypeSerializer`

**Related issue(s)**:

Part of #6122

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

### CODE REVIEW

**Review by jascks — APPROVED** [review]
LGTM

**Review by edwin-greene — COMMENTED** [review]
Looks good, but sonar found 2 code smells

**Comment by steven-sheehy** [comment]
> Looks good, but sonar found 2 code smells

True, but I intentionally didn't remove the unused parameter in this PR and will leave it for a follow up as it's a widespread change.

**Review by jnels124 — APPROVED** [review]
LGTM

**Pull request merged**
