### PR TITLE
adjust full_page_write postgres setting

### LINKED ISSUE #8728: Performance Test with full_page_writes Turned Back On
### Description

When upgrading the gke cluster, it was noticed that the coordinator replica had to rebuild from scratch. After investigation, this is because patroni attempts to issue a pg_rewind command which requires full_page_writes to be turned on in postgres config.

```
2024-07-08 19:46:30,459 INFO: Local timeline=3 lsn=16/6A000028
2024-07-08 19:46:30,681 INFO: primary_timeline=4
2024-07-08 19:46:30,683 INFO: primary: history=1	0/20000A0	no recovery target specified
2	14/BC0000A0	no recovery target specified
3	16/69F10F98	no recovery target specified
2024-07-08 19:46:30,837 INFO: running pg_rewind from mirror-citus-coord-0
2024-07-08 19:46:31,668 INFO: running pg_rewind from dbname=postgres user=postgres host=10.4.1.9 port=7433 target_session_attrs=read-write
2024-07-08 19:46:31,814 INFO: pg_rewind exit code=1
2024-07-08 19:46:31,814 INFO:  stdout=
2024-07-08 19:46:31,814 INFO:  stderr=pg_rewind: error: full_page_writes must be enabled in the source server

2024-07-08 19:46:31,845 ERROR: Failed to rewind from healty primary: mirror-citus-coord-0
2024-07-08 19:46:31,846 WARNING: remove_data_directory_on_rewind_failure is set. removing...
2024-07-08 19:46:31,846 INFO: Removing data directory: /var/lib/postgresql/data
2024-07-08 19:46:33,783 INFO: Lock owner: mirror-citus-coord-0; I am mirror-citus-coord-1
2024-07-08 19:46:33,870 INFO: trying to bootstrap from leader 'mirror-citus-coord-0'
```

### Steps to reproduce

Create a situation where the timeline diverges for the coordinator and coordinator replica (this occurred naturally by having a fully running system and performing a gke node upgrade. This caused importer to be running against the primary while the replica was going through the zfs bootstrap process)

### Additional context

_No response_

### Hedera network

other

### Version

v0.108.0

### Operating system

None

### PR DESCRIPTION
**Pull request by jnels124**
**Description**:
* adjust full_page_writes setting for coordinator

**Related issue(s)**:

Fixes #8728 

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

### CODE REVIEW

**Comment by jnels124** [comment]
full_page_writes true on worker and coordinator
both-parse
both-insert
full_page_writes true on coordinator only
coordinator-only-parse
coordinator-only-insert

**Review by jascks — APPROVED** [review]
LGTM

**Review by xin-hedera — APPROVED** [review]
LGTM

**Review by mgoelswirlds — APPROVED** [review]
LGTM

**Pull request merged**
