### PR TITLE
Update mainnet-staging to v0.108.0-beta1

### PR DESCRIPTION
**Pull request by steven-sheehy**
**Description**:

Update mainnet-staging to v0.108.0-beta1

**Related issue(s)**:

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

### CODE REVIEW

**Review by jascks — DISMISSED** [review]
LGTM

**Review by jnels124 — APPROVED** [review]
LGTM

**Review by xin-hedera — DISMISSED** [review]

**Review by jnels124 — CHANGES_REQUESTED** [review]
we need to configure the target namespaces. `testkube.test.targets`

```
testkube:
  test:
    targets:
    - namespace: mainnet
       release: mirror
    - namespace: mainnet-citus
       release: mirror
```

**Review by jnels124 — APPROVED** [review]
LGTM

**Review by jascks — APPROVED** [review]
LGTM

**Pull request merged**
