### PR TITLE
Add freeze and unfreeze missing validations

### LINKED ISSUE #7894: Add missing Precompile Logic validations
### Problem

After investigation #7822. 
It seem that there are some missing validations in some of the logics that were copied from services.

FreezeLogic, UnfreezeLogic
setFrozen has missing logic from services 
setFrozen - `validateTrue(token.hasFreezeKey(), TOKEN_HAS_NO_FREEZE_KEY);`

### Solution

We need to add those missing logics code validations 
Add tests for them.

### Alternatives

_No response_

### PR DESCRIPTION
**Pull request by zhpetkov**
**Description**:
After changes, we don't have missing logic that validates the freeze and unfreeze state of the token.  I add `changeFrozenState` in `TokenRelationship` which modifies the state of the `frozen` property.  Before the property modification, the method performs validation, that the respective token has a freeze key. I replace `setFrozen` with `changeFrozenState` in `FreezeLogic`, `UnfreezeLogic` because this will help to properly change the state of the token. Make needed modifications in `TokenRelationshipTest`, `FreezeLogicTest`, `UnfreezeLogicTest`. The changes are borrowed from Hedera Services. 

**Related issue(s)**:

Fixes #7894 

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

### CODE REVIEW

**Comment by bilyana-gospodinova** [comment]
I think we need one more test in FreezeLogicTest and in UnfreezeLogicTest that cover the scenario when there is no freeze key set and `tokenRelationship.changeFrozenState` throws an exception.

**Comment by kselveliev** [comment]
We need to modify our Fungible and nft tokens in acceptance tests (TokenClient) otherwise ->
```
Then I freeze "FUNGIBLE" token, unfreeze and get status
Then I freeze "NFT" token, unfreeze and get status
```
will fail

**Comment by steven-sheehy** [comment]
> We need to modify our Fungible and nft tokens in acceptance tests (TokenClient) otherwise ->
> 
> ```
> Then I freeze "FUNGIBLE" token, unfreeze and get status
> Then I freeze "NFT" token, unfreeze and get status
> ```
> 
> will fail

We should not have failing acceptance tests on main since they get deployed automatically. So it will need to be part of this PR.

**Review by steven-sheehy — APPROVED** [review]
LGTM

**Review by bilyana-gospodinova — APPROVED** [review]
LGTM

**Pull request merged**
