### PR TITLE
Unit tests for code path executed after DB response

### LINKED ISSUE #244: Add unit tests for REST API to verify the code path after getting information from DB query
**Problem**
Current unit tests for REST APIs only validate generation of the right SQL query.

**Solution**
Add unit tests that validate the code path that gets executed after getting information from the database queries.

**Alternatives**
None

**Additional Context**
None

### PR DESCRIPTION
**Pull request by atul-hedera**
**Detailed description**:
Added code to return mock responses from the DB queries to validate the code path that gets executed after getting responses from the DB.

**Which issue(s) this PR fixes**:
Fixes #244

**Special notes for your reviewer**:
`npm install && npm test`

(or run individually as npm test accounts.test.js; npm test balances.test.js; or npm test transactions.test.js

**Checklist**
- [ ] Documentation added
- [x] Tests updated

### CODE REVIEW

**Comment by mike-burrage-hedera** [comment]
Changed to WIP for the timebeing. we'll open up the master branch again after OA. For now, just bug fixes there.

**Comment by steven-sheehy** [comment]
Something went awry with your last push. There's now 48 commits, missing signoff on some commits and the diff shows changes that are already in master.

**Comment by atul-hedera** [comment]
I am creating a new PR. Will delete this brach after that

**Comment by atul-hedera** [comment]
See PR: 291 (https://github.com/hashgraph/hedera-mirror-node/pull/291)

**Pull request closed without merging**
