### PR TITLE
Add a REST API Java module

### LINKED ISSUE #6544: Add a hedera-mirror-rest-java module
### Problem

As a developer, I'd like to avoid adding technical debt by adding new REST APIs to a new Java based REST API.

### Solution

* Add a `hedera-mirror-rest-java` module patterned after the `hedera-mirror-web3` module.
* Add a `RestJavaApplication`
* Add a temporary `DummyController` for testing
* Create a `hedera-mirror-rest-java` Docker image
* Add the module to CI

### Alternatives

_No response_

### PR DESCRIPTION
**Pull request by mgoelswirlds**
**Description**:

Add a new rest-java module with basic functionality.

* Add a `rest-java` module
* Add a dummy controller
* Add OpenAPI generation of the view model
* Add the new module to CI

**Related issue(s)**:

Fixes #6544 

**Notes for reviewer**:

**Checklist**

- [x] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

### CODE REVIEW

**Comment by mgoelswirlds** [comment]
Followup to this PR:
1. Pull the openapi generation to a common task/config.
2. Adding mapstruct to map model (code generation from different beans)
3. Add the data source.
4. Add a more useful example with TokenAllowances.

**Review by jascks — APPROVED** [review]
There is a lot to it. Looks good!

**Review by xin-hedera — APPROVED** [review]
LGTM

**Comment by jnels124** [comment]
LGTM

**Pull request merged**
